language: ruby
bundler_args: --without extras
script: "bundle exec rake"
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.1.1
  - jruby-19mode
  - rbx
matrix:
  allow_failures:
    - rvm: rbx

